source 'https://github.com/hconnectdx/ios-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'PoliSDK_Example' do
  pod 'PoliSDK', :path => '../'

  target 'PoliSDK_Tests' do
    inherit! :search_paths

    pod 'Nimble', '~> 10.0.0'
  end
end
